### ISSUE TITLE
feat: Add ability to cache compilers between runs

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/setup-fortran#98]
It would be extremely useful if the Action  had a key option `cache`, similar to `setup-python` that could enable/disable caching the downloaded compilers and the setup.

## Suggestion

```yaml
    - uses: fortran-lang/setup-fortran@v1.6.1
      id: setup-fortran
      with:
        compiler: ${{ matrix.toolchain.compiler }}
        version: ${{ matrix.toolchain.version }}
        cache: true  # optional, default is false
```
